apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-app-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: flask-app
    rules:
    - alert: PodDown
      expr: up == 0
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "Pod is down in your cluster!"
